{% set version = "2.15.4" %}

package:
  name: django-grappelli
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-grappelli/django-grappelli-{{ version }}.tar.gz
  sha256: 4c85062109fc8bd7e8399a88f146d934c57c8fba9865aa3ecd6392b9bed60ead

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - django

test:
  imports:
    - grappelli
    - grappelli.templatetags
    - grappelli.views
    - grappelli.dashboard
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://django-grappelli.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A jazzy skin for the Django Admin-Interface

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
