{% set version = "3.0.3" %}

package:
  name: django-grappelli
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-grappelli/django-grappelli-{{ version }}.tar.gz
  sha256: 7d60304200f4ea202862fda3b0efaa91c70280841ca22b1b22f49f1017ed2afc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - django

test:
  imports:
    - grappelli
    - grappelli.templatetags
    - grappelli.views
    - grappelli.dashboard
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://django-grappelli.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A jazzy skin for the Django Admin-Interface

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
