{% set version = "2.13.4" %}

package:
  name: django-grappelli
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-grappelli/django-grappelli-{{ version }}.tar.gz
  sha256: be89f14f0d5e8be0bf0dd389dadacd4074beb87c3d6f128d05c4d1e5b20a65a8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django

test:
  imports:
    - grappelli
    - grappelli.templatetags
    - grappelli.tests
    - grappelli.views

about:
  home: http://django-grappelli.readthedocs.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A jazzy skin for the Django Admin-Interface.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
