{% set version = "2.10.1" %}
{% set sha256 = "dedc5118c2271008937e5e8df37982310af884d29983359da0ebc2292b0b17fd" %}

package:
  name: django-grappelli
  version: {{ version }}

source:
  fn: django-grappelli-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/django-grappelli/django-grappelli-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django

test:
  imports:
    - grappelli
    - grappelli.templatetags
    - grappelli.tests
    - grappelli.views

about:
  home: http://django-grappelli.readthedocs.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A jazzy skin for the Django Admin-Interface.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
