travis:
  secure:
    BINSTAR_TOKEN: 07GgSGnraei2cmw2fG/V2jJv3eKko4ZHIOhPUpee/fM3OEnQL2UDEZxzjIUsWaWY/TxKlRx1XcLgIQfJmWuBwPAJN97R5RJQE8iwxM2f9dMdLPkeF4Q4lqwwrAgvaaGCMyjTZLEg/kRvwq9+5vgYu3YTvErKJ+wgHv0iC8RE/jXBFXDiBycG7r/HdPR+9D/hf7iKDSc0xiK3q9CvNVMF0kjORtLCv18IVs2oxSoxaj0Gv6mEIr+C3C8ZKEdTEOAlWMZhJ9pagUTF7aHnMJ//ltEuGUt9vxCkjozCYigi3x62x/YN/YtmN3VLBLKhT3f2chwRAgVR/znsbRY8SqIGBVojOYPVEjR7iuKnw0M4uoQr9C+JjPO3JHWFgDPPGTrMyTp0MHV7KvhikxtdnhQnCgC9fG8zc+56QaXI+ibdKqtKq/ReIxVpNK0UQKx0K2P59wFqPK7mUy+htig6kjNzXIkma1ZrHg3KrDitydK149d3X8Dte5uEgZTBzffUY87EA02gCX/p7YqRwnl7H6ySGTxOeQID6oEWWqnjiL9V1tMR4Ck2nh+frTiDzhIzsE7Y1XEi3I6W8m5lvtyFfsX6TRsQzp+5U5XXaABO1OqIrBtwyH8Fk62pcu9G6PN93VJAO/BczE4uhLP1cMVJXSEYmHlBABdJUqrvisQ7FLvtQTE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
