travis:
  secure:
    BINSTAR_TOKEN: ULElslR/m1sF+U1OnZ/zoj0ffNys3efcouDl6dpDVtW9xO1n0AKBp7ws8cb08LRfi7Isv6JR3D0q62/4QkyVoe1Nha8qKM7GxkwrEzTWULUzTbcpSqRYxFj/hsXzA5+ctGxH9YxuAc/qCIJ2vA0qYWvhu6D9MCw/a1evCw/MI5Mjh+1GdfAU9edQTdj1gN15/9eBz26OsT3V/rirFxc4YjelgZRNStMQr/mZZ63/BSAuHoBecCPZcq/yrvmypg2k6QyErfC8/fFcdZZsn4T8fYok6/lJ9XRlJzZ6TCBimx0m+qFsM9/5jk7EO16TNZsgZs6XwTKGl5N/Yq52AaC7DHC9FSD6DFblsB8ZtErJ6AkP69yaj3GjWQZz3Z5x1Pw900pMm83HX5NG8Pm2mjAGhdoit9517QBqzKTNVgE3qrSCbRynXxJ8OgWRwu0lqFoV3i33szPvivtJ4EZxYADrKwwdkCKb25mI6+eWNB1qjcMBzJgdq9Cj7mZvGW+EAs/jwDSShYFiogxb6iz4ZLZHJl4FiOicODHIMy45tyXz7+DTPb+9NOW14IbybJRMJ9HELWWs2RNtPLuADfwKLDnTo0PIofWKh6eHOVuSOoLzPo0ARaSAPCkr+Ntvxgqc3KDCwD04xutuPtkCJpNUTTnOKh/l8Xwky3X6M6KislgQpi4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
