travis:
  secure:
    BINSTAR_TOKEN: aMuHykkyXULCSHoEuopkxJyf3PUNR9cniwpt//aSrWH0gT9mi6odZmOUUC+eXtBWgG82Zpd+ape65JNNKIxK4s4JBywxRmsaBbrPEgxPi4ROhMOFtemYGCS2Y+2wXTbc28xCF19elnoZCcFLyU9tMMLQGiYgih7Y2D0gJSYJtQ3RpD8phtr1mgPahfCcQMBHKgF0UnnngtVH19YmSZqEzu+NI9N4JmYwr4c57K5hCWIu8gWdMS9T5QoJM2Eh381T55JoVAjBvUfiXIBpB2HmgdfbTbRfiKpdN6QhOz0yvan2XefqrnAC2uQb9wmBv70KPCiPQ8v149/F1Ad9ISC5TgVNDz4gjQVmuooek26hr6VXKjxt46t1wp+VPt+cc3MgBj1+waGN8VQD1uSXkjEXCnL+vsTuhYW3sB8o3Et23DUPP8mwuquG2LfJ+7Gm4AjMVZ4drqJ0OxiajO9q41OFwx84RZ19eq87jXyaTntmj3TT5Iej13EOdsvcWNLImPgro6djLAeTpBj1y1DXavO9mNlXvDoGs+bni+GDxVYTan7bmQS0YDrhea7RK/xKc9iD/q9F/8DxOGkf7bsHRY1ukCRpI9DutOzVJpwp32rjc6+xsSDrbnK01U+oHdGXGTVxlPNBl//UJkUZ7oLAcOgU0Ba4h270UcW8mRLwIVbI/88=
appveyor:
  secure:
    BINSTAR_TOKEN: !!binary |
      TVA0aFpZeWxEeVVXRXNydDN1M2NvZDJzYkZlUndVemlIMDJtdlFPZGJqc1RPL2wxeUl4RGtQLzc2
      clNJamNHQw==
